version: '3.8'

services:
  gemini-api:
    build: .
    container_name: gemini_api_service
    ports:
      - "8008:8000" # Map HOST port 8008 to CONTAINER port 8000
    env_file:
      - .env
    restart: unless-stopped